#!/bin/bash
remove_row_by_id(){
       table_name=$1
       primary_key=$2
    
   local table_file="$HOME/${table_name}.csv"  # 
    if [ ! -f $table_file ]; then 
         echo "Table not found"
            return 1 
            fi 
    # search for primary key 
    if grep -q "${primary_key}" "$table_file"; then 
    sed -i "/${primary_key},/d" "$table_file"
    echo "Row deleted successfuly"
    else 
    echo "ROW NOT FOUND"
    return 1 
    fi 
}
remove_row_by_id "$1" "$2"

